name: 自动刷课

on:
  schedule:
    - cron: '0 3 * * *'      # 每天凌晨3点自动运行
  workflow_dispatch:         # 支持手动运行

jobs:
  brush:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v6

      - name: 设置 Python 环境
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行自动刷课
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COURSE_LIST: ${{ secrets.COURSE_LIST }}
        run: python main.py --username "${USERNAME}" --password "${PASSWORD}" --courses "${COURSE_LIST}" --headless --no-login-check
