name: 自动刷课

on:
  schedule:
    - cron: '0 3 * * *'      # 每天凌晨3点
  workflow_dispatch:

jobs:
  brush:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v6

      - name: 设置 Python 环境
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行自动刷课
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COURSE_LIST: ${{ secrets.COURSE_LIST }}
        run: echo -e "$USERNAME\n$PASSWORD\n$COURSE_LIST\n\n" | python main.py -u "$USERNAME" -p "$PASSWORD" -l "$COURSE_LIST"
